Reclama5/Areas/Admin/Controllers/AdvertisinglistsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;
using Reclama5.Domain.Entities;
using Reclama5.Service;
namespace Reclama5.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdvertisinglistsController : Controller
    {
        private readonly DataManager dataManager;
        // для сохранения титульных картинок
        private readonly IWebHostEnvironment hostingEnvironment;
        public AdvertisinglistsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            // по id ищем услугу в базн днных если конструкция не найдена то создаем новый объект класса если найдена то выбираем из базы данных
            var entity = id == default ? new Advertisinglist() : dataManager.Advertisinglists.GetAdvertisinglistById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(Advertisinglist model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    // название картинки сохраняем в свойство
                    model.TitleImagePath = titleImageFile.FileName;

                    //Для получения полного пути к каталогу wwwroot применяется свойство WebRootPath объекта IWebHostEnvironment. Для копирования файла в папку  images создается поток FileStream, в который записывается файл с помощью метода CopyToAsync
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.Advertisinglists.SaveAdvertisinglist(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.Advertisinglists.DeleteAdvertisinglist(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Reclama5/Areas/Admin/Views/Advertisinglists/Edit.cshtml
@model Advertisinglist
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div class="col-md-12">
    <h2>@strTitle</h2>

    <!-- методом пост отправляем на сервер enctype="multipart/form-data" браузер будет знать, что вместе с формой надо передать файлы-->
    <form asp-area="Admin" asp-controller="Advertisinglists" asp-action="Edit" method="post" enctype="multipart/form-data">
        <fieldset>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>

            <label asp-for="Text"></label>
            <textarea asp-for="Text"></textarea>
            <span asp-validation-for="Text"></span>

            <label asp-for="Number"></label>
            <input asp-for="Number" />
            <span asp-validation-for="Number"></span>

            <label asp-for="Type"></label>
            <input asp-for="Type" />
            <span asp-validation-for="Type"></span>

            <label asp-for="Square"></label>
            <input asp-for="Square" />
            <span asp-validation-for="Square"></span>

            <label asp-for="Address"></label>
            <input asp-for="Address" />
            <span asp-validation-for="Address"></span>

            <label asp-for="FieldA"></label>
            <input asp-for="FieldA" />
            <span asp-validation-for="FieldA"></span>

            <label asp-for="FieldB"></label>
            <input asp-for="FieldB" />
            <span asp-validation-for="FieldB"></span>

            <label asp-for="Title"></label>
            <input asp-for="Title" />
            <span asp-validation-for="Title"></span>

            <label asp-for="Subtitle"></label>
            <input asp-for="Subtitle" />
            <span asp-validation-for="Subtitle"></span>

            <label asp-for="TitleImagePath"></label>
            <input type="file" name="titleImageFile" id="titleImageFile" />
            <div>
                <img class="img-block" src="~/images/@Model.TitleImagePath" />
            </div>

            <label asp-for="MetaTitle"></label>
            <input asp-for="MetaTitle" />
            <span asp-validation-for="MetaTitle"></span>

            <label asp-for="MetaDescription"></label>
            <input asp-for="MetaDescription" />
            <span asp-validation-for="MetaDescription"></span>


            <label asp-for="MetaKeywords"></label>
            <input asp-for="MetaKeywords" />
            <span asp-validation-for="MetaKeywords"></span>

        </fieldset>
        <button type="submit">Сохранить</button>
    </form>
</div>

<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>