Reclama5/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;
using Reclama5.Models;




namespace Reclama5.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

     
    }
}

Reclama5/Areas/Admin/Controllers/TextFieldsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;
using Reclama5.Domain.Entities;
using Reclama5.Service;


namespace Reclama5.Areas.Admin.Controllers 
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        //внедряем датаменеджер чтобы иметь доступ к база данных
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public TextFieldsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

Reclama5/Controllers/AdvertisingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Reclama5.Controllers
{
    public class AdvertisingController : Controller
    {
     
        public IActionResult Documentation()
        {
            return View();
        }
        public IActionResult Design()
        {
            return View();
        }
    }
}

Reclama5/Controllers/AuctionsController.cs
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;

namespace Reclama5.Controllers
{
    public class AuctionsController : Controller
    {
        private readonly DataManager dataManager;

        public AuctionsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        // 
        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                // конкретная аукцион
                return View("Show", dataManager.AuctionItems.GetAuctionItemById(id));
            }
            // если id равен дефолдному значению то показывет список всех аукционов
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageAuctions");
            return View(dataManager.AuctionItems.GetAuctionItems());
        }
    }
}

Reclama5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;

namespace Reclama5.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }

        public IActionResult Management()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageManagement"));
        }

        public IActionResult About()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageAbout"));
        }
    }
}

Reclama5/Areas/Admin/Views/Home/Index.cshtml
@model TextField
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;

}



<div class="frame">
    <h1>Редактировать страницы сайта</h1>
    <div class="inner-frame">
        <a class="custom-anchor anchor" asp-area="Admin" asp-controller="Auctions" asp-action="Index" asp-route-id=""> Список торгов</a>
        <a class="custom-anchor anchor" asp-area="Admin" asp-controller="Advertising" asp-action="Index" asp-route-id="">Список рекламных конструкций</a>
        <a class="custom-anchor anchor" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Редактировать страницу "Главная"</a>
        <a class="custom-anchor anchor" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Редактировать страницу "Торги"</a>
        <a class="custom-anchor anchor" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageAdvertisings">Редактировать страницу "Сдача рекламных поверхностей"</a>
        <a class="custom-anchor anchor" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Редактировать страницу "Контакты"</a>
        <a class="custom-anchor anchor" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageAbout">Редактировать страницу "О предприятии"</a>
        <a class="custom-anchor anchor" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageManagement">Редактировать страницу "Руководство"</a>
    </div>

    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
        <input type="submit" value="Выйти" />
    </form>
</div>