Reclama5/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;
using Reclama5.Models;




namespace Reclama5.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

     
    }
}

Reclama5/Controllers/AdministrativeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Reclama5.Controllers
{
    public class AdministrativeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Extend()
        {
            return View();
        }
        public IActionResult Reregister()
        {
            return View();
        }
        public IActionResult Duplicate()
        {
            return View();
        }
    }
}

Reclama5/Controllers/AdvertisingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Reclama5.Controllers
{
    public class AdvertisingController : Controller
    {
     
        public IActionResult Documentation()
        {
            return View();
        }
        public IActionResult Design()
        {
            return View();
        }
    }
}

Reclama5/Controllers/AdvertisingsController.cs
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;

namespace Reclama5.Controllers
{
    public class AdvertisingsController : Controller
    {
        private readonly DataManager dataManager;

        public AdvertisingsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                // конкретная конструкция 
                return View("Show", dataManager.Advertisinglists.GetAdvertisinglistById(id));
            }
            // если id равен дефолдному значению то показывет список всех конструкций
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageAdvertisings");
            return View(dataManager.Advertisinglists.GetAdvertisinglists());
        }
    }
}

Reclama5/Controllers/AuctionsController.cs
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;

namespace Reclama5.Controllers
{
    public class AuctionsController : Controller
    {
        private readonly DataManager dataManager;

        public AuctionsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        // 
        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                // конкретная аукцион
                return View("Show", dataManager.AuctionItems.GetAuctionItemById(id));
            }
            // если id равен дефолдному значению то показывет список всех аукционов
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageAuctions");
            return View(dataManager.AuctionItems.GetAuctionItems());
        }
    }
}

Reclama5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;

namespace Reclama5.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }

        public IActionResult Management()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageManagement"));
        }

        public IActionResult About()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageAbout"));
        }
    }
}

Reclama5/Views/Home/About.cshtml
@model TextField
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
@{
    @if (Model?.MetaTitle == null)
    {
        ViewBag.Title = "Реклама и услуги";
    }
    else
    {
        ViewBag.Title = Model.MetaTitle;
    }

    @if (Model?.MetaDescription == null)
    {
        ViewBag.Description = "Оформление, продление, переоформление паспорта средства наружной рекламы. Размещение рекламы на рекламных щитах, рекламных пилонах, лайтпостерах в городе Бобруйске. Аренда помещений. Торги на право размещения средства наружной рекламы";
    }
    else
    {
        ViewBag.Descriptione = Model.MetaDescription;
    }
    @if (Model?.MetaKeywords == null)
    {
        ViewBag.Keywords = "реклама, рекламный щит, рекламный пилон, лайтпостер, рекламное агентство, реламная организация, разместить рекламу на улице, заказать услуги по рекламе, размещение рекламы, реклама на транспорте, паспортизация рекламы, оформление рекламы, реклама и услуги, средства наружной рекламы в Бобруйске";
    }
    else
    {
        ViewBag.Keywords = Model.MetaKeywords;
    }
}


@if (Model?.Text == null)
{
    <div class="main-areaab">
        <article>
            <h1>О предприятие</h1>
            <p>
                Коммунальное производственное унитарное предприятие «Реклама и услуги» было основано в 2006 году
                решением Бобруйского исполнительного комитета №22-4 от 25.10.2006.
            </p>
            <div class="line" style="width: 15%;"></div>
            <p>
                Решением Бобруйского горисполкома от 19 ноября 2021г. №20-196 «О размещении (распространении) и  наружной рекламы
                и её средств на территории города Бобруйска» (далее – Решение №20-196),
                коммунальному производственному унитарному предприятию «Реклама и услуги» делегированы полномочия по приему,
                подготовке к рассмотрению, принятию административного решения об отказе в принятии
            </p>

            <ul>
                <li>заявления на  выдачу разрешения на размещение средства наружной рекламы (далее – разрешение),</li>
                <li>заявления на продление действия разрешения, </li>
                <li>заявления на выдачу дубликата разрешения,</li>
                <li>заявления на переоформление разрешения.</li>
            </ul>
            <div class="line" style="width: 15%;"></div>
            <p>
                Коммунальное производственное унитарное предприятие «Реклама и услуги» Решением  №20-196 определенно как специализированная
                организация по проведению торгов на право размещения средства рекламы, в том числе средства наружной рекламы,
                на государственном недвижимом имуществе.
            </p>
            <div class="line" style="width: 15%;"></div>
            <p>
                Решением Бобруйского горисполкома от 15 октября 2021г. №20-76 «О наделении полномочиями» (далее – Решение №20-76),
                коммунальное производственное унитарное предприятие «Реклама и услуги» уполномочено на:
                проведение мероприятий, направленных на сбор информации о соблюдении субъектами хозяйствования на территории
                города Бобруйска законодательства о рекламе, в том числе о соответствии размещенной наружной рекламы и ее средств
                условиям выданных разрешений и заключенных договоров на размещение средства наружной рекламы, с предоставлением
                информации в управление торговли и услуг горисполкома
            </p>
            <div class="line" style="width: 15%;"></div>
            <p>
                Согласно Решению №20-76 коммунальное производственное унитарное предприятие «Реклама и услуги»
                осуществляет контроль за
            </p>
            <ul>
                <li>правильностью исчисления платы за размещение средства наружной рекламы;</li>
                <li>полным и своевременным поступлением в бюджет города Бобруйска платы за размещение средства наружной рекламы. </li>
            </ul>
            <div class="line" style="width: 15%;"></div>
            <p>
                Государственное предприятие "Реклама и услуги" является оператором наружной рекламы в городе Бобруйске,
                предоставляющим собственную сеть наружной рекламы для размещения рекламы третьих лиц, имущество которого находится в коммунальной собственности города Бобруйска.
            </p>
        </article>
    </div>
}
else
{
    <div class="contacts">
        @Html.Raw(Model?.Text)
    </div>
}

Reclama5/Views/Home/Contacts.cshtml
@model TextField
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
@{
    @if (Model?.MetaTitle == null)
    {
        ViewBag.Title = "Реклама и услуги";
    }
    else
    {
        ViewBag.Title = Model.MetaTitle;
    }

    @if (Model?.MetaDescription == null)
    {
        ViewBag.Description = "Оформление, продление, переоформление паспорта средства наружной рекламы. Размещение рекламы на рекламных щитах, рекламных пилонах, лайтпостерах в городе Бобруйске. Аренда помещений. Торги на право размещения средства наружной рекламы";
    }
    else
    {
        ViewBag.Descriptione = Model.MetaDescription;
    }
    @if (Model?.MetaKeywords == null)
    {
        ViewBag.Keywords = "реклама, рекламный щит, рекламный пилон, лайтпостер, рекламное агентство, реламная организация, разместить рекламу на улице, заказать услуги по рекламе, размещение рекламы, реклама на транспорте, паспортизация рекламы, оформление рекламы, реклама и услуги, средства наружной рекламы в Бобруйске";
    }
    else
    {
        ViewBag.Keywords = Model.MetaKeywords;
    }
}


@if (Model?.Text == null)
{
    <div class="main-areacon">
        <article>
            <h1 style="text-align: left;">Контакты</h1>
            <div class="fon">
                <h3>Коммунальное производственное унитарное предприятие "Реклама и услуги" </h3>
                <p>юридический адрес: 213809, г. Бобруйск, ул. М. Горького, д. 41, к. 2</p>
                <h3>Время работы предприятия:</h3>
                <p>Понедельник – пятница:8.00 – 17.00 Обеденный перерыв: 13.00 – 14.00Выходные: суббота, воскресенье</p>
            </div>
            <div style="border: 1px solid grey; padding: 1rem; "><script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A8d7a08356c19a7552f95ec6bd292e92d9c73383d24e221811840d1e9f695f710&amp;max-width=622&amp;min-width=auto&amp;height=421&amp;lang=ru_RU&amp;scroll=true"></script></div>
        </article>
        <article class="table">
            <table>
                <tr>
                    <td>Директор</td>
                    <td>+375 225 77 63 89</td>
                </tr>
                <tr>
                    <td>Бухгалтерия</td>
                    <td>+375 225 74 00 44</td>
                </tr>
                <tr>
                    <td>
                        Оформление,переоформление,
                        продление, выдача дубликата
                        паспорта средства наружной рекламы
                    </td>
                    <td>+375 225 77-65-71</td>
                </tr>
                <tr>
                    <td>
                        Оплата в городской бюджет
                        за размещение средства наружной рекламы
                    </td>
                    <td>+375 225 71 50 05</td>
                </tr>
                <tr>
                    <td>Дизайнер</td>
                    <td>+375 225 76 00 78</td>
                </tr>
                <tr>
                    <td>
                        Размещение рекламы
                        на рекламных конструкциях
                        предприятия
                    </td>
                    <td>+375 225 77-65-71</td>
                </tr>
                <tr>
                    <td>
                        Услуги по сбору документов
                        для оформления паспорта
                    </td>
                    <td> +375 225 76 00 78</td>
                </tr>
            </table>
            <div class="fon">
                <h3>Банковские реквизиты </h3>
                <p>
                    Счет № (IBAN): BY34 AKBB 3012 1123 9117 6710 0000 ОАО «АСБ «Беларусбанк»

                    Код банка: (BIC) AKBBBY2Х

                    г. Бобруйск

                    код 153801760

                    УНП 790373119

                    ОКПО 293206137000
                </p>
                <h3>Реквизиты для внесения платы за размещение (распространение) наружной рекламы:</h3>
                <p>
                    Получатель платежа: Главное управление Министерства финансов Республики Беларусь по Могилевской области

                    УНП 700451296

                    Счет № (IBAN): BY08 AKBB 3600 7030 0001 9000 0000

                    г. Минск

                    Код банка (BIC) AKBB BY 2X

                    Назначение платежа: за размещение (распространение) наружной рекламы

                    Код платежа в бюджет: 05519
                </p>
            </div>
        </article>
    </div>
}
else
{
    <div class="contacts">
        @Html.Raw(Model?.Text)
    </div>
}

Reclama5/Views/Home/Index.cshtml
@model TextField
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;

}



<main class="main-area">
    <!-- ==== О предприятии ==== -->
    <figure class="intro-content1">
        <img src="images/фото1.png" alt="foto" />
    </figure>

    <article class="intro-content2">
        <h1>Предприятие</h1>
        <nav>
            <ul class="menu-list1">
                <li><a asp-area="" asp-controller="Home" asp-action="About"> О предприятии</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Management">Руководство</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a></li>
            </ul>
        </nav>
    </article>

    <!-- ==== Администратиыные процедуры ==== -->
    <figure class="intro-content1">
        <img src="images/фото2.png" width="800" alt="foto" />
    </figure>
    <article class="intro-content2">
        <h1>Административные процедуры</h1>
        <nav>
            <ul class="menu-list1">
                <li><a asp-area="" asp-controller="Administrative" asp-action="Index">Получение разрешения</a></li>
                <li><a asp-area="" asp-controller="Administrative" asp-action="Extend">Продление действия разрешения</a></li>
                <li><a asp-area="" asp-controller="Administrative" asp-action="Reregister">Переформление действия разрешения</a></li>
                <li><a asp-area="" asp-controller="Administrative" asp-action="Duplicate">Выдача дубликата разрешения</a></li>
            </ul>
        </nav>
    </article>

    <!-- ==== Торги ==== -->
    <figure class="intro-content1">
        <img src="images/фото3.png" width="800" alt="foto" />
    </figure>

    <article class="intro-content2">
        <h1>Торги</h1>
        <nav>
            <ul class="menu-list1">
                <li><a asp-area="" asp-controller="Auctions" asp-action="Index" asp-route-id=""> Аукционы и конкурсы</a></li>
            </ul>
        </nav>
    </article>

    <!-- ==== Сдача рекламных поверхностей ==== -->
    <figure class="intro-content1">
        <img src="images/фото4.png" width="800" alt="foto" />
    </figure>

    <article class="intro-content2">
        <h1>Услуги</h1>
        <nav>
            <ul class="menu-list1">
                <li><a asp-area="" asp-controller="Advertisings" asp-action="Index" asp-route-id=""> Сдача рекламных поверхностей</a></li>
                <li><a asp-area="" asp-controller="Advertising" asp-action="Documentation">  Сбор документов для оформления паспорта </a></li>
                <li><a asp-area="" asp-controller="Advertising" asp-action="Design">  Дизайн </a></li>
            </ul>
        </nav>
    </article>
</main>

Reclama5/Views/Home/Management.cshtml
@model TextField
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
@{
    @if (Model?.MetaTitle == null)
    {
        ViewBag.Title = "Реклама и услуги";
    }
    else
    {
        ViewBag.Title = Model.MetaTitle;
    }

    @if (Model?.MetaDescription == null)
    {
        ViewBag.Description = "Оформление, продление, переоформление паспорта средства наружной рекламы. Размещение рекламы на рекламных щитах, рекламных пилонах, лайтпостерах в городе Бобруйске. Аренда помещений. Торги на право размещения средства наружной рекламы";
    }
    else
    {
        ViewBag.Descriptione = Model.MetaDescription;
    }
    @if (Model?.MetaKeywords == null)
    {
        ViewBag.Keywords = "реклама, рекламный щит, рекламный пилон, лайтпостер, рекламное агентство, реламная организация, разместить рекламу на улице, заказать услуги по рекламе, размещение рекламы, реклама на транспорте, паспортизация рекламы, оформление рекламы, реклама и услуги, средства наружной рекламы в Бобруйске";
    }
    else
    {
        ViewBag.Keywords = Model.MetaKeywords;
    }
}


@if (Model?.Text == null)
{
    <div class="main-areacon">

        <article>
            <h1 style="text-align: left; font-size: 1.8rem;">Вышестоящая организация</h1>
            <div class="fon1">
                <h1>
                    Управление торговли и услуг
                    Бобруйского городского исполнительного комитета
                </h1>

                <h3>АДРЕС:</h3>
                <p>г. Бобруйск, пл. Ленина, 1</p>
                <h3>Семенчук Елена Анатольевна</h3>
                <p>
                    Начальник управление торговли и услуг
                    Бобруйского городского исполнительного комитета
                </p>
                <h3>ТЕЛЕФОН:</h3>
                <p>8-0225-68-00-40</p>
            </div>
        </article>

        <article>
            <h1 style="text-align: left; font-size: 1.8rem;">РУКОВОДСТВО ПРЕДПРИЯТИЯ</h1>
            <div class="fon1">
                <h1>Петрусевич Владимир Владимирович</h1>
                <p>директор</p>
                <h3>ПРИЕМ ГРАЖДАН:</h3>
                <p>
                    Первая и третяя среда месяца c 8:00 до 13:00
                    по предварительной записи.При  временном отсутствии  по уважительным причинам (отпуск, болезнь, командиовка) в день личного приема рруководителем, личный прием осуществляет юрисконсульт Жигунов Роман Игоревич г. Бобруйск, ул. М. Горького, 41, каб. 3 тел. 77-63-89
                </p>
                <h3>АДРЕС:</h3>
                <p>г.Бобруйск, ул. М. Горького, 41</p>
                <h3>E-MAIL:</h3>
                <p>reclamariubobr@gmail.com</p>
            </div>
        </article>
        <article>
            <div class="fon1">
                <h1>ШинкоренкоЛюдмила Витальевна</h1>
                <p>главный бухгалтер</p>
                <h3>Телефон:</h3>
                <p>74-00-44</p>
                <h3>АДРЕС:</h3>
                <p>г.Бобруйск, ул. М. Горького, 41</p>
                <h3>E-MAIL:</h3>
                <p>reclamariubobr@gmail.com</p>
            </div>
        </article>
        <article>
            <div class="fon1">
                <p style=" padding-top: 10px;">
                    Предварительная запись на личный приём осуществляется по номеру:
                    г. Бобруйск, ул. М. Горького, 41, каб. 1,тел./факс  +375 (225) 77-65-71
                </p>
            </div>
        </article>
    </div>

}
else
{

    <div class="contacts">
        @Html.Raw(Model?.Text)
    </div>
}