Reclama5/Areas/Admin/Controllers/AuctionItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;
using Reclama5.Domain.Entities;
using Reclama5.Service;

namespace Reclama5.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuctionItemsController : Controller
    {
        private readonly DataManager dataManager;
        // для сохранения титульных картинок
        private readonly IWebHostEnvironment hostingEnvironment;
        public AuctionItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            // по id ищем услугу в базн днных если аукцион не найден то создаем новый объект класса если найден то выбираем из базы данных
            var entity = id == default ? new AuctionItem() : dataManager.AuctionItems.GetAuctionItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(AuctionItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    // название картинки сохраняем в свойство
                    model.TitleImagePath = titleImageFile.FileName;

                    //Для получения полного пути к каталогу wwwroot применяется свойство WebRootPath объекта IWebHostEnvironment. Для копирования файла в папку  images создается поток FileStream, в который записывается файл с помощью метода CopyToAsync
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.AuctionItems.SaveAuctionItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.AuctionItems.DeleteAuctionItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Reclama5/Areas/Admin/Controllers/AuctionsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;
using Reclama5.Domain.Entities;
using Reclama5.Service;


namespace Reclama5.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuctionsController : Controller
    {

        private readonly DataManager dataManager;

        public AuctionsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.AuctionItems.GetAuctionItems());
        }

    }
}

Reclama5/Controllers/AuctionsController.cs
using Microsoft.AspNetCore.Mvc;
using Reclama5.Domain;

namespace Reclama5.Controllers
{
    public class AuctionsController : Controller
    {
        private readonly DataManager dataManager;

        public AuctionsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        // 
        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                // конкретная аукцион
                return View("Show", dataManager.AuctionItems.GetAuctionItemById(id));
            }
            // если id равен дефолдному значению то показывет список всех аукционов
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageAuctions");
            return View(dataManager.AuctionItems.GetAuctionItems());
        }
    }
}

Reclama5/Areas/Admin/Views/Auctions/Index.cshtml
@model IQueryable<AuctionItem>

@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}
<script asp-src-include="~/js/table.js"></script>

<main class="main-areap">
    <article>
        <button>
            <a asp-area="Admin" asp-controller="AuctionItems" asp-action="Edit" asp-route-id="">Добавить торги</a>
        </button>
        <div class="table">
            <table id="example" class="display" style="text-align: center ">
                <thead>
                    <tr>
                        <th>Редоктирование</th>
                        <th>Удаление</th>
                        <th>Адрес</th>
                    </tr>
                </thead>
                @if (Model.Any())
                {
                    @foreach (var entity in Model)
                    {
                        <tr>
                            <td>
                                <a asp-area="Admin" asp-controller="AuctionItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                            </td>
                            <td>
                                <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="AuctionItems" asp-action="Delete" method="post">
                                    <input type="hidden" name="id" value="@entity.Id">
                                    <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                                </form>
                            </td>
                            <td>
                                <a asp-area="" asp-controller="Auctions" asp-action="Index" asp-route-id="@entity.Id">
                                    @($"{entity.Title}")
                                </a>
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>
    </article>

    <div>
        <form asp-area="Admin" asp-controller="Home" asp-action="Index" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>

</main>